import importlib

_collect = importlib.import_module("qfte_engine.01_collect")
_normalize = importlib.import_module("qfte_engine.02_normalize")
_market = importlib.import_module("qfte_engine.03_market")
_sport = importlib.import_module("qfte_engine.04_sport")
_calibration = importlib.import_module("qfte_engine.05_calibration")
_scores = importlib.import_module("qfte_engine.06_scores")
_value = importlib.import_module("qfte_engine.07_value")
_risk = importlib.import_module("qfte_engine.08_risk")
_discipline = importlib.import_module("qfte_engine.09_discipline")
_output = importlib.import_module("qfte_engine.10_output")
_monitor = importlib.import_module("qfte_engine.11_monitor")


def analyser_match(match):
    print("=== PIPELINE START ===")
    data = _collect.collecter_donnees(match)
    print("ETAPE 1 OK")
    data = _normalize.normaliser_donnees(data)
    print("ETAPE 2 OK")
    data = _market.analyser_marche(data)
    print("ETAPE 3 OK")
    data = _sport.analyser_sport(data)
    print("ETAPE 4 OK")
    data = _calibration.calibrer_probabilites(data)
    print("ETAPE 5 OK")
    data = _scores.predire_scores(data)
    print("ETAPE 6 OK")
    data = _value.detecter_value(data)
    print("ETAPE 7 OK")
    data = _risk.gerer_risques(data)
    print("ETAPE 8 OK")
    data = _discipline.appliquer_discipline(data)
    print("ETAPE 9 OK")
    data = _output.formater_recommandation(data)
    print("ETAPE 10 OK")
    data = _monitor.surveiller(data)
    print("ETAPE 11 OK")
    print("=== PIPELINE END ===")
    return data
