import importlib

_collect = importlib.import_module("qfte_engine.01_collect")
_normalize = importlib.import_module("qfte_engine.02_normalize")
_context = importlib.import_module("qfte_engine.13_context")
_calendrier = importlib.import_module("qfte_engine.19_calendrier_foot")
_calendrier_basket = importlib.import_module("qfte_engine.20_calendrier_basket")
_market = importlib.import_module("qfte_engine.03_market")
_stats_avancees = importlib.import_module("qfte_engine.21_stats_avancees")
_sport = importlib.import_module("qfte_engine.04_sport")
_validation = importlib.import_module("qfte_engine.12_validation")
_calibration = importlib.import_module("qfte_engine.05_calibration")
_copula = importlib.import_module("qfte_engine.17_copula")
_scores = importlib.import_module("qfte_engine.06_scores")
_value = importlib.import_module("qfte_engine.07_value")
_risk = importlib.import_module("qfte_engine.08_risk")
_discipline = importlib.import_module("qfte_engine.09_discipline")
_output = importlib.import_module("qfte_engine.10_output")
_monitor = importlib.import_module("qfte_engine.11_monitor")
_partenariat = importlib.import_module("qfte_engine.15_partenariat")
_amplificateur = importlib.import_module("qfte_engine.16_amplificateur")
_aura = importlib.import_module("qfte_engine.22_aura")
_oracle = importlib.import_module("qfte_engine.23_oracle")
_chronos = importlib.import_module("qfte_engine.24_chronos")
_instinct = importlib.import_module("qfte_engine.25_instinct")


def analyser_match(match):
    data = _collect.collecter_donnees(match)
    data = _normalize.normaliser_donnees(data)
    data = _context.analyser_contexte(data)
    data = _calendrier.analyser_calendrier(data)
    data = _calendrier_basket.analyser_calendrier_basket(data)
    data = _market.analyser_marche(data)
    data = _stats_avancees.calculer_stats_avancees(data)
    data = _sport.analyser_sport(data)
    data = _validation.valider_coherence(data)
    data = _calibration.calibrer_probabilites(data)
    data = _copula.appliquer_copule(data)
    data = _scores.predire_scores(data)
    data = _value.detecter_value(data)
    data = _risk.gerer_risques(data)
    data = _discipline.appliquer_discipline(data)
    data = _output.formater_recommandation(data)
    data = _partenariat.apposer_signature(data)
    data = _amplificateur.amplifier(data)
    data = _aura.calculer_aura(data)
    data = _oracle.calculer_oracle(data)
    data = _chronos.calculer_chronos(data)
    data = _instinct.calculer_instinct(data)                  # 💀 Couche INSTINCT
    data = _monitor.surveiller(data)
    return data
